# Generated by Django 3.1.4 on 2020-12-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaPemilik', models.CharField(max_length=50)),
                ('idBarang', models.IntegerField()),
                ('namaBarang', models.CharField(max_length=50)),
                ('deskripsiBarang', models.TextField()),
                ('urlFoto', models.URLField()),
                ('hargaBarang', models.FloatField()),
                ('jumlahStok', models.IntegerField()),
                ('rating', models.FloatField()),
                ('stokRate', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='BarangModel',
        ),
    ]
