# Generated by Django 3.1.4 on 2020-12-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judulArtikel', models.CharField(max_length=10)),
                ('abstraksiArtikel', models.CharField(max_length=255)),
                ('isiArtikel', models.TextField()),
            ],
        ),
    ]
