# Generated by Django 3.1.4 on 2020-12-25 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='idArtikel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
