# Generated by Django 3.1.4 on 2020-12-25 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_artikel_idartikel'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
