# Generated by Django 3.1.4 on 2020-12-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20201226_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='gambarThumbnail',
            field=models.ImageField(default='thumbnail_folder/None/no-img.jpg', upload_to='thumbnail_folder/'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='judulArtikel',
            field=models.CharField(max_length=50),
        ),
    ]
