# Generated by Django 3.1.4 on 2020-12-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20201226_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='gambarThumbnail',
        ),
        migrations.AlterField(
            model_name='artikel',
            name='abstraksiArtikel',
            field=models.TextField(max_length=255),
        ),
    ]
