# Generated by Django 3.1.4 on 2020-12-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20201226_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='idArtikel',
            field=models.IntegerField(unique=True),
        ),
    ]
