# Generated by Django 3.1.4 on 2020-12-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20201227_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='gambarThumbnail',
            field=models.ImageField(default='thumbnail_folder/None/no-img.jpg', upload_to='thumbnail_folder/'),
        ),
    ]
