# Generated by Django 3.1.4 on 2020-12-27 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0002_auto_20201227_0702'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keranjang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listBarang', models.ManyToManyField(to='barang.Barang')),
            ],
        ),
        migrations.AddField(
            model_name='kontributormodel',
            name='keranjang',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.keranjang'),
        ),
    ]
