# Generated by Django 3.1.4 on 2020-12-27 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0002_auto_20201227_0702'),
        ('shop', '0003_auto_20201227_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keranjangmodel',
            name='listBarang',
            field=models.ManyToManyField(blank=True, null=True, to='barang.Barang'),
        ),
        migrations.AlterField(
            model_name='kontributormodel',
            name='keranjang',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.keranjangmodel'),
        ),
    ]
