# Generated by Django 3.1.4 on 2020-12-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0002_auto_20201227_0702'),
        ('shop', '0004_auto_20201227_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keranjangmodel',
            name='listBarang',
            field=models.ManyToManyField(blank=True, to='barang.Barang'),
        ),
    ]
