# Generated by Django 3.1.4 on 2020-12-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0002_auto_20201227_0702'),
        ('shop', '0006_auto_20201227_1821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BarangTransaksi',
            new_name='BarangKeranjang',
        ),
    ]
