# Generated by Django 3.1.4 on 2020-12-27 16:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0002_auto_20201227_0702'),
        ('shop', '0007_auto_20201227_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktuDibuat', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('totalHarga', models.FloatField()),
                ('kontributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.kontributormodel')),
            ],
        ),
        migrations.CreateModel(
            name='PengirimanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaEkspedisi', models.CharField(max_length=100)),
                ('nomorResi', models.CharField(max_length=20)),
                ('transaksi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.transaksimodel')),
            ],
        ),
        migrations.CreateModel(
            name='PembayaranModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktuPembayaran', models.DateTimeField(auto_now_add=True)),
                ('totalPembayaran', models.FloatField()),
                ('transaksi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.transaksimodel')),
            ],
        ),
        migrations.CreateModel(
            name='BarangTrx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtyTrx', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('barangTrx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.barang')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.transaksimodel')),
            ],
        ),
    ]
