# Generated by Django 3.1.4 on 2020-12-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_barangtrx_pembayaranmodel_pengirimanmodel_transaksimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksimodel',
            name='metodePengiriman',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
