# Generated by Django 3.1.4 on 2020-12-26 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LembagaSosialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaLs', models.TextField()),
                ('deskripsi', models.TextField()),
                ('urlFoto', models.TextField()),
                ('namaPimpinan', models.TextField()),
                ('jenis', models.TextField()),
                ('kapasitas', models.TextField()),
                ('kebutuhan', models.TextField()),
                ('nomorTeleponLs', models.TextField()),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DonasiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('alasanPembatalan', models.TextField()),
                ('jenisBarang', models.TextField()),
                ('metodePengiriman', models.TextField()),
                ('tanggalPengiriman', models.TextField()),
                ('alamatJemput', models.TextField()),
                ('namaDonatur', models.TextField()),
                ('tanggalDonasi', models.TextField()),
                ('lembagaSosial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donasi.lembagasosialmodel')),
            ],
        ),
    ]
